os:
    - linux
    # travis does not support python on osx yet (https://github.com/travis-ci/travis-ci/issues/4729)
language: python
python:
    - "3.4"
before_install:
    - sudo pip install spyder notebook nbconvert nbformat pyyaml psutil tqdm
    - sudo pip install fasteners pygments ipython ptpython networkx pydotplus
    # for testing
    - sudo pip install nose
install: "python setup.py install"
sudo: required
before_script: cd test
script:
    - ./run_tests ../sos/jupyter/test 
notifications:
    email:
        recipients:
            - ben.bob@gmail.com
        on_success: never
        on_failure: always
