os:
    - linux
    # travis does not support python on osx yet (https://github.com/travis-ci/travis-ci/issues/4729)
language: python
python:
    - "3.5"
before_install:
    - sudo pip install spyder notebook ipykernel nbconvert nbformat pyyaml psutil tqdm
    - sudo pip install fasteners pygments ipython ptpython networkx pydotplus
    # for testing
    - sudo pip install nose
install: "sudo python setup.py install"
sudo: required
before_script: cd sos/jupyter/test
script:
    - python test_action.py
notifications:
    email:
        recipients:
            - ben.bob@gmail.com
        on_success: never
        on_failure: always
