language: python3
before_install:
      - conda create -n ipykernel_py2 python=2 ipykernel
      - source activate ipykernel_py2
      - python -m ipykernel install --user
script:
     - python setup.py install
