os:
    - linux
    # travis does not support python on osx yet (https://github.com/travis-ci/travis-ci/issues/4729)
language: python
python:
    - "3.4"
install: "python setup.py install"
before_script: cd test
script:
    - ./run_tests ../sos/jupyter/test 
notifications:
    email:
        recipients:
            - ben.bob@gmail.com
        on_success: never
        on_failure: always
